services:
  auto-crypto-trade:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: auto-crypto-base
    container_name: auto-crypto-trade
    ports:
      - "8080:8080"  # 将容器的 8080 端口映射到主机
    environment:
      - PYTHONUNBUFFERED=1  # 确保日志输出立即可见