services:
  auto-crypto-trade:
    build:
      context: ./strategy_agent
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: auto-crypto-base
    container_name: auto-crypto-trade
    ports:
      - "8080:8080"

  celery-beat-auto-trade:
    build:
      context: ./strategy_agent
      dockerfile: Dockerfile
    command: celery -A app.tasks beat --loglevel=info
  
  auto-trade-worker:
    build:
      context: ./strategy_agent
      dockerfile: Dockerfile
    command: celery -A app.tasks worker --loglevel=info --queues=auto_trade_queue

  newslabeler-web:
    build:
      context: ./news_labeler
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    restart: unless-stopped

  newslabeler-worker:
    build:
      context: ./news_labeler
      dockerfile: Dockerfile
    command: python -m app.label_worker
    restart: unless-stopped
